<a href="https://colab.research.google.com/github/Keithni/deeplearning/blob/master/test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
a = np.ones(3)
print(a)
import tensorflow as tf
w = tf.Variable(tf.random_normal(shape=[3,3],mean=0,stddev=1.0,dtype=tf.float32))

with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())
  print(sess.run(w))

[1. 1. 1.]
[[ 1.8043091   0.30281034 -0.0960013 ]
 [ 0.967039   -1.5752832   0.49453807]
 [-1.3700291  -0.23232439 -0.69159985]]
